import { Badge } from "./ui/badge";
import { Button } from "./ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";

interface TestSuggestion {
	title: string;
	description: string;
	value: number;
	difficulty: "low" | "medium" | "high";
	estimatedRuntime?: number;
	testType: "unit" | "integration" | "e2e";
	uncoveredLines: number[];
	prompt: string;
	cursorDeeplink: string;
}

interface TestSuggestionsProps {
	suggestions: TestSuggestion[];
	loading?: boolean;
	error?: string | null;
}

function getDifficultyVariant(
	difficulty: "low" | "medium" | "high"
): "success" | "warning" | "error" | "neutral" {
	if (difficulty === "low") return "success";
	if (difficulty === "medium") return "warning";
	return "error";
}

function getValueVariant(value: number): "success" | "warning" | "error" | "neutral" {
	if (value >= 0.7) return "success";
	if (value >= 0.4) return "warning";
	return "neutral";
}

function getTestTypeVariant(
	testType: "unit" | "integration" | "e2e"
): "info" | "warning" | "error" {
	if (testType === "unit") return "info";
	if (testType === "integration") return "warning";
	return "error";
}

function formatRuntime(ms?: number): string {
	if (!ms) return "Unknown";
	if (ms < 1000) return `${ms}ms`;
	return `${(ms / 1000).toFixed(1)}s`;
}

export default function TestSuggestions({ suggestions, loading, error }: TestSuggestionsProps) {
	if (loading) {
		return (
			<Card>
				<CardHeader>
					<CardTitle>AI Test Suggestions</CardTitle>
					<CardDescription>Generating test suggestions...</CardDescription>
				</CardHeader>
				<CardContent>
					<div className="text-center text-muted-foreground py-8">Loading...</div>
				</CardContent>
			</Card>
		);
	}

	if (error) {
		return (
			<Card>
				<CardHeader>
					<CardTitle>AI Test Suggestions</CardTitle>
					<CardDescription>Failed to generate suggestions</CardDescription>
				</CardHeader>
				<CardContent>
					<div className="text-sm text-error bg-error-muted/20 p-4 rounded-lg">{error}</div>
				</CardContent>
			</Card>
		);
	}

	if (suggestions.length === 0) {
		return (
			<Card>
				<CardHeader>
					<CardTitle>AI Test Suggestions</CardTitle>
					<CardDescription>No suggestions available</CardDescription>
				</CardHeader>
				<CardContent>
					<div className="text-sm text-muted-foreground">
						No test suggestions generated yet. This may happen if the file has 100% coverage or if
						there was an error generating suggestions.
					</div>
				</CardContent>
			</Card>
		);
	}

	return (
		<Card>
			<CardHeader>
				<CardTitle>AI Test Suggestions</CardTitle>
				<CardDescription>
					{suggestions.length} test suggestion{suggestions.length !== 1 ? "s" : ""} generated by AI
				</CardDescription>
			</CardHeader>
			<CardContent className="space-y-4">
				{suggestions.map((suggestion) => (
					<Card key={`${suggestion.title}-${suggestion.testType}`} className="border-border">
						<CardHeader className="pb-3">
							<div className="flex items-start justify-between gap-4">
								<div className="flex-1">
									<CardTitle className="text-base">{suggestion.title}</CardTitle>
									<CardDescription className="mt-1">{suggestion.description}</CardDescription>
								</div>
								<div className="flex flex-wrap gap-2">
									<Badge variant={getValueVariant(suggestion.value)}>
										Value: {(suggestion.value * 100).toFixed(0)}%
									</Badge>
									<Badge variant={getDifficultyVariant(suggestion.difficulty)}>
										{suggestion.difficulty.charAt(0).toUpperCase() + suggestion.difficulty.slice(1)}
									</Badge>
									<Badge variant={getTestTypeVariant(suggestion.testType)}>
										{suggestion.testType}
									</Badge>
									{suggestion.estimatedRuntime && (
										<Badge variant="neutral">~{formatRuntime(suggestion.estimatedRuntime)}</Badge>
									)}
								</div>
							</div>
						</CardHeader>
						<CardContent className="pt-0">
							<div className="space-y-3">
								{suggestion.uncoveredLines.length > 0 && (
									<div>
										<div className="text-xs text-muted-foreground mb-1">Covers lines:</div>
										<div className="flex flex-wrap gap-1">
											{suggestion.uncoveredLines.slice(0, 20).map((line) => (
												<Badge key={line} variant="neutral" className="font-mono text-xs">
													{line}
												</Badge>
											))}
											{suggestion.uncoveredLines.length > 20 && (
												<Badge variant="neutral" className="font-mono text-xs">
													+{suggestion.uncoveredLines.length - 20} more
												</Badge>
											)}
										</div>
									</div>
								)}
								<Button
									onClick={() => {
										window.location.href = suggestion.cursorDeeplink;
									}}
									variant="default"
									size="sm"
									className="w-full sm:w-auto"
								>
									<svg
										xmlns="http://www.w3.org/2000/svg"
										width="16"
										height="16"
										viewBox="0 0 24 24"
										fill="none"
										stroke="currentColor"
										strokeWidth="2"
										strokeLinecap="round"
										strokeLinejoin="round"
										className="mr-2"
										aria-hidden="true"
									>
										<title>Cursor</title>
										<path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4" />
										<polyline points="10 17 15 12 10 7" />
										<line x1="15" y1="12" x2="3" y2="12" />
									</svg>
									Generate Test in Cursor
								</Button>
							</div>
						</CardContent>
					</Card>
				))}
			</CardContent>
		</Card>
	);
}
